# Generated by Django 4.2.1 on 2023-06-30 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='LName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('city', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('t_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('pos', models.CharField(max_length=2)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('ovr', models.IntegerField()),
                ('three', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('standShot', models.IntegerField()),
                ('moveShot', models.IntegerField()),
                ('passAcc', models.IntegerField()),
                ('dribble', models.IntegerField()),
                ('dot', models.IntegerField()),
                ('drive', models.IntegerField()),
                ('dunk', models.IntegerField()),
                ('layup', models.IntegerField()),
                ('backdown', models.IntegerField()),
                ('postMove', models.IntegerField()),
                ('closeShot', models.IntegerField()),
                ('oBoard', models.IntegerField()),
                ('dBoard', models.IntegerField()),
                ('perDefense', models.IntegerField()),
                ('postDefense', models.IntegerField()),
                ('intimidation', models.IntegerField()),
                ('steal', models.IntegerField()),
                ('block', models.IntegerField()),
                ('reconition', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('vertical', models.IntegerField()),
                ('team', models.ForeignKey(default='FA', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.team')),
            ],
        ),
    ]
