# Generated by Django 4.2.4 on 2023-08-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fourTeams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='sixTeams',
            field=models.IntegerField(default=0),
        ),
    ]
