# Generated by Django 4.2.1 on 2023-07-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='t_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
