# Generated by Django 4.2.1 on 2023-06-06 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('city', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('pos', models.CharField(max_length=2)),
                ('height', models.CharField(max_length=10)),
                ('ovr', models.IntegerField()),
                ('three', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('close', models.IntegerField()),
                ('dribble', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('perimeter_defense', models.IntegerField()),
                ('post_defense', models.IntegerField()),
                ('steal', models.IntegerField()),
                ('block', models.IntegerField()),
                ('test', models.IntegerField(default='1')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.team')),
            ],
        ),
    ]
