# Generated by Django 4.2.1 on 2023-07-03 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_player_first_name_alter_player_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='userTeam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default='FAA', on_delete=django.db.models.deletion.CASCADE, to='league.team'),
        ),
    ]
