# Generated by Django 4.2.1 on 2023-06-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
