# Generated by Django 4.2.2 on 2023-06-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default='FA', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.team'),
        ),
    ]
