# Generated by Django 4.2.1 on 2023-07-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_team_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='physical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='playmaker',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='post',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='shooter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='slashing',
            field=models.IntegerField(default=0),
        ),
    ]
