# Generated by Django 4.2.1 on 2023-06-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='id',
            new_name='t_id',
        ),
    ]
