# Generated by Django 4.2.1 on 2023-07-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_player_defense_player_physical_player_playmaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shooter',
            field=models.IntegerField(),
        ),
    ]
