# Generated by Django 4.2.1 on 2023-06-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_fname'),
    ]

    operations = [
        migrations.CreateModel(
            name='LName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=55)),
            ],
        ),
    ]
