# Generated by Django 4.2.1 on 2023-07-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_alter_player_shooter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='defense',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='physical',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='playmaker',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='post',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='slashing',
            field=models.IntegerField(),
        ),
    ]
