# Generated by Django 4.2.1 on 2023-07-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_player_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contract',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
