# Generated by Django 4.2.1 on 2023-07-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_player_contract_player_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='contract',
        ),
        migrations.AddField(
            model_name='player',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
