# Generated by Django 4.2.1 on 2023-07-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_remove_player_contract_player_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
