# Generated by Django 4.2.1 on 2023-07-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_team_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('awayTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='league.team')),
                ('homeTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='league.team')),
            ],
        ),
    ]
