# Generated by Django 4.2.1 on 2023-07-22 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_alter_team_fourteams_alter_team_sixteams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='fourTeams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sixTeams',
        ),
    ]
