# Generated by Django 4.2.3 on 2023-08-03 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_offer'),
        ('league', '0018_team_fourteams_team_sixteams'),
    ]

    operations = [
    ]
