# Generated by Django 4.2.4 on 2023-08-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_team_fourteams_team_sixteams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='fourTeams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sixTeams',
        ),
    ]
