# Generated by Django 4.2.4 on 2023-08-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_offer'),
        ('league', '0020_game_loser_game_winner_record'),
    ]

    operations = [
    ]
