# Generated by Django 4.2.4 on 2023-08-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_merge_0013_offer_0020_game_loser_game_winner_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='league.team'),
        ),
    ]
