# Generated by Django 4.2.4 on 2023-08-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_alter_record_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('reg', 'Regular Season'), ('playoffs', 'Playoffs'), ('draft', 'Draft'), ('free', 'Free Agency')], max_length=15)),
                ('week', models.IntegerField()),
            ],
        ),
    ]
