# Generated by Django 4.2.4 on 2023-08-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='stage',
            field=models.CharField(choices=[('reg', 'Regular Season'), ('playoffs', 'Playoffs'), ('draft', 'Draft'), ('free', 'Free Agency')], default='reg', max_length=15),
        ),
    ]
