# Generated by Django 4.2.4 on 2023-08-11 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_alter_time_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='playoffGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('first', 'First Round'), ('second', 'Second Round'), ('semis', 'Conference Finals'), ('finals', 'Finals')], max_length=25)),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoffAway', to='league.team')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoffHome', to='league.team')),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoffLoser', to='league.team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoffWinner', to='league.team')),
            ],
        ),
    ]
