# Generated by Django 4.2.4 on 2023-08-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0025_playoffgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playoffgame',
            name='round',
            field=models.CharField(choices=[('first', 'First Round'), ('second', 'Second Round'), ('semis', 'Conference Finals'), ('finals', 'Finals')], max_length=25, null=True),
        ),
    ]
