# Generated by Django 4.2.4 on 2023-08-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_alter_playoffgame_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoffStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoffTeam', to='league.team')),
            ],
        ),
    ]
