# Generated by Django 4.2.4 on 2023-08-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_playoffstandings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayoffStandings',
            new_name='PlayoffTeam',
        ),
    ]
