# Generated by Django 4.2.4 on 2023-08-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_rename_playoffstandings_playoffteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoffteam',
            name='conference',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
