# Generated by Django 4.2.4 on 2023-08-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_playoffteam_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoffgame',
            name='conference',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
