# Generated by Django 4.2.4 on 2023-08-15 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0031_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='league.team'),
        ),
    ]
