# Generated by Django 4.2.4 on 2023-08-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_team_fourteams_team_sixteams'),
        ('league', '0032_alter_record_team'),
    ]

    operations = [
    ]
