# Generated by Django 4.2.4 on 2023-08-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0033_merge_20230821_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='fourTeams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sixTeams',
        ),
        migrations.AddField(
            model_name='draft',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick', to='league.player'),
        ),
        migrations.AddField(
            model_name='draft',
            name='userPick',
            field=models.BooleanField(default=False),
        ),
    ]
