# Generated by Django 4.2.4 on 2023-08-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0034_remove_team_fourteams_remove_team_sixteams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.IntegerField()),
            ],
        ),
    ]
